paginate:     1

author:
  name:      Konrad Höffner 
  url:       http://www.imise.uni-leipzig.de/Mitarbeiter/Konrad.Hoeffner.jsp 

plugins:
  - jekyll-paginate

markdown: kramdown
theme: jekyll-theme-cayman
title: SNIK Technical Blog
name: SNIK Technical Blog 
description: Technical Blog for the SNIK Project about a Semantic Network of Hospital Information Management 
permalink: pretty
encoding: utf-8

kramdown:
    auto_ids: true
