baseurl:      ""
paginate:     1

author:
  name:      Konrad Höffner 
  url:       http://www.imise.uni-leipzig.de/Mitarbeiter/Konrad.Hoeffner.jsp 

gems:
  - jekyll-paginate

markdown: kramdown
title: SNIK Ontology
name: SNIK Ontology
description: Semantic Network of Hospital Information Management 
permalink: pretty
encoding: utf-8
